name: context_demo
on: 
     workflow_dispatch:
     push:
env:
  variable1: "context_demo"
  varaible2: "second_Variable"   
jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      variable1: 'changed1'
      variable2: 'changed2'
    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}" 
          echo "SHA: ${{ github.sha }}" 
          echo "Actions: ${{ github.action }}"
          echo "Workflow: ${{ github.workflow }}"
      
      - name: Retrieve variable
        run: |
          echo "Variable Value : ${{ env.variable1 }}"
      
      - name: Print env Variables
        env:
          varaible2: 'step'
        run: |
          echo "Variable Value : ${{ env.varaible1 }}"
          echo "Overwritten Value : ${{ env.varaible2 }}"
      
      - name: Print Env variables 
        run: |
          echo "Variable Value : ${{ env.varaible1 }}"
          echo "Overwritten  Value : ${{ env.varaible2 }}"

