name:  reuse

on:
  
  workflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Show the triggers
        run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
      - name: show runner_name
        run: echo "Runner Os:$RUNNER_OS"
